#!/bin/sh

mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts

ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

mount -t proc none /proc
mount -t sysfs none /sys

export PS1="\u@busybox:\w\# "

cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

        _       _     __ _                  
  /\/\ (_)_ __ (_)   / /(_)_ __  _   ___  __
 /    \| | '_ \| |  / / | | '_ \| | | \ \/ /
/ /\/\ \ | | | | | / /__| | | | | |_| |>  < 
\/    \/_|_| |_|_| \____/_|_| |_|\__,_/_/\_\ 


Welcome to mini_linux

!

root=$(cat /proc/cmdline | tr ' ' '\n' | grep root | cut -d= -f 2)

if [ -b $root ]
then
	rootmnt=/mnt
	mkdir $rootmnt
	mount $root $rootmnt
	mount -n -o move /dev ${rootmnt}/dev
	mount -n -o move /sys ${rootmnt}/sys
	mount -n -o move /proc ${rootmnt}/proc
	exec switch_root -c /dev/console ${rootmnt} /sbin/init
else
	serial=$(cat /proc/cmdline | tr ' ' '\n' | grep console | cut -d= -f 2)
	
	while :
	do
		/sbin/getty 115200 /dev/$serial
	done
fi
