#!/bin/sh

mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts

ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /run
mount -t tmpfs none /tmp

cat <<!
Boot took $(cut -d' ' -f1 /proc/uptime) seconds
!

serial=$(grep -E -o "\bconsole=\w+" /proc/cmdline | grep -E -o "ttyS0|hvc0|ttyAMA0|ttySAC0" | tail -n 1)
root=$(grep -oE "root=/dev/\w+" /proc/cmdline | tail -n 1 | cut -d "=" -f 2)
init=$(grep -oE "init=(\w|/)+" /proc/cmdline | tail -n 1 | cut -d "=" -f 2)

if [ ! "$root" = "" ] ; then
	if [ "$init" = "" ] ; then
		init=/sbin/init
	fi

	rootmnt=/mnt
	mkdir $rootmnt
	mount $root $rootmnt
	mount -n -o move /dev ${rootmnt}/dev
	mount -n -o move /sys ${rootmnt}/sys
	mount -n -o move /proc ${rootmnt}/proc
	mount -n -o move /run ${rootmnt}/run
	mount -n -o move /tmp ${rootmnt}/tmp
	exec switch_root -c /dev/console ${rootmnt} $init
fi

if [ -f /usr/sbin/sshd ]; then
	/usr/sbin/sshd
else
	telnetd -l /bin/login_
fi

while :
do
	if [ -f /usr/sbin/agetty ]; then
		/usr/sbin/agetty -a root $serial
	else
        	/sbin/getty -n -l /bin/login_ 115200 /dev/$serial
	fi
done
