#!/bin/sh

mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts

ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /run
mount -t tmpfs none /tmp

cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

        _       _     __ _                  
  /\/\ (_)_ __ (_)   / /(_)_ __  _   ___  __
 /    \| | '_ \| |  / / | | '_ \| | | \ \/ /
/ /\/\ \ | | | | | / /__| | | | | |_| |>  < 
\/    \/_|_| |_|_| \____/_|_| |_|\__,_/_/\_\ 


Welcome to mini_linux


!

hostname initramfs

if [ -e /sys/class/net/eth0 ]; then
	ip addr add 192.168.1.34/24 dev eth0
	ip link set up eth0
	ip route add default via 192.168.1.1
	nc -z 192.168.1.2 2 &
	telnetd -l /bin/login_
fi

stty rows 47 cols 211

serial=$(grep -E -o "\bconsole=\w+" /proc/cmdline | grep -E -o "ttyS0|hvc0|ttyAMA0" | tail -n 1)

while :
do
        /sbin/getty -n -l /bin/login_ 115200 /dev/$serial
done
