#!/bin/bash

mkdir -p /etc/netns/route/
echo nameserver 8.8.8.8 > /etc/netns/route/resolv.conf

ip netns add route
ip netns exec route ip link set lo up
ip link add veth0 type veth peer name eth0 netns route
ip link add veth1 type veth peer name lan0 netns route
ip link set veth0 master eth-br
ip link set veth1 master lan-br
ip link set veth0 up
ip link set veth1 up
ip netns exec route ip addr add 192.168.1.254/24 dev eth0
ip netns exec route ip addr add 10.0.0.254/24 dev lan0
ip netns exec route ip link set eth0 up
ip netns exec route ip link set lan0 up
ip netns exec route ip route add default via 192.168.1.1 dev eth0 metric 10

ip netns exec route sh -c 'echo 1 > /proc/sys/net/ipv4/ip_forward'
ip netns exec route ip tuntap add mode tun dev tun0
ip netns exec route ip addr add 198.18.0.1/15 dev tun0
ip netns exec route ip link set tun0 up
ip netns exec route ip route add default via 198.18.0.1 dev tun0 metric 1
ip netns exec route iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
ip netns exec route nohup tun2socks-linux-amd64-v3 -device tun0 -proxy socks5://192.168.1.2:10808 -interface eth0 > /var/log/route-tun2socks.log &
ip netns exec route dnsmasq --strict-order --except-interface=lo --interface=lan0 --bind-interfaces --dhcp-range=10.0.0.10,10.0.0.20 --pid-file=/var/run/dnsmasq-lan-br.pid --dhcp-leasefile=/var/run/dnsmasq-lan-br.leases --dhcp-no-override -O 6,8.8.8.8
