#!/bin/bash

export PATH=/bin:/sbin:/usr/local/bin/

dmesg -n 1
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t proc none /proc
ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

hostname fedora-L1

ip a | grep eth0 > /dev/null
if [ $? -eq 0 ]
then
	ip link set up eth0
	if [[ $(hostname) = "fedora-L1" ]]
	then
		ip link add name eth-br type bridge
		ip link set eth-br up
		ip addr add 192.168.1.9/24 dev eth-br
		ip link set dev eth0 master eth-br
	else
		ip addr add 192.168.1.11/24 dev eth0
	fi
	ip route add default via 192.168.1.1
	ncat -z 192.168.1.2 22 &
	/sbin/sshd &
fi

mount_vdb () {
	if [ -e /dev/vdb ]
	then
		e2fsck -y /dev/vdb 2> /dev/null > /dev/null
		mount /dev/vdb /a
	fi
}

mount_vdb &

while :
do
	if [ -e /dev/hvc0 ]
	then
		/usr/sbin/agetty -a root hvc0
	else
		/usr/sbin/agetty -a root ttyS0
	fi
done
