#!/bin/bash

export PATH=/bin:/sbin:/usr/local/bin/

dmesg -n 1
mkdir /dev/pts
mount -t devpts devpts /dev/pts 2> /dev/null
mount -t sysfs none /sys 2> /dev/null
mount -t proc none /proc
ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

stty rows 45 cols 190
hostname fedora-vm

ip a 2> /dev/null | grep eth0 >& /dev/null
if [ $? -eq 0 ]
then
	ip link set up eth0
	if [[ $(hostname) = "fedora-L1" ]]
	then
		ip link add name eth-br type bridge
		ip link set eth-br up
		ip addr add 192.168.1.9/24 dev eth-br
		ip link set dev eth0 master eth-br
	else
		ip addr add 192.168.1.11/24 dev eth0
	fi
	ip route add default via 192.168.1.1
	ncat -z 192.168.1.2 22 &
	/sbin/sshd &
fi

while :
do
	ip a >& /dev/null
	if [ $? -eq 0 ]
	then
		/usr/sbin/agetty -a root hvc0
	else
		bash --init-file /root/.bashrc
	fi
done
