#!/bin/bash

export PATH=/bin:/sbin:/usr/local/bin/

mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t sysfs none /sys
mount -t proc none /proc
ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

stty rows 55 cols 211
hostname fedora-vm

serial=$(cat /proc/cmdline | grep -oE "console=\w+" | cut -d= -f 2)

while :
do
	/usr/sbin/agetty -a root $serial
done
